---
Name: freshdesk
After:
  - 'framework/*'
  - 'cms/*'
---
UserDefinedForm_Controller:
  extensions:
    - UserDefinedForm_ControllerFreshdeskExtension
UserDefinedForm:
  extensions:
    - UserDefinedFormFreshdeskExtension
Injector:
  FreshdeskClient:
    factory: 'FreshdeskClientFactory'
Director:
  rules:
    'freshdesksso': FreshdeskSSO
